// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEnKIVlijlOFJeJlcv9I1iMDu2sBUbBE',
    appId: '1:411403822361:web:e3746c42009fba48f29188',
    messagingSenderId: '411403822361',
    projectId: 'farmercompanion',
    authDomain: 'farmercompanion.firebaseapp.com',
    storageBucket: 'farmercompanion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOC6Sk67R0KENVyN_kePrFnnOso9PQH8',
    appId: '1:411403822361:android:61e7a6648a3125f4f29188',
    messagingSenderId: '411403822361',
    projectId: 'farmercompanion',
    storageBucket: 'farmercompanion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1-pHnvd158W-sWXZ4FXav4dQUOQNecA',
    appId: '1:411403822361:ios:c5232646f0e8f2f6f29188',
    messagingSenderId: '411403822361',
    projectId: 'farmercompanion',
    storageBucket: 'farmercompanion.appspot.com',
    iosBundleId: 'com.example.flutterFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1-pHnvd158W-sWXZ4FXav4dQUOQNecA',
    appId: '1:411403822361:ios:c5232646f0e8f2f6f29188',
    messagingSenderId: '411403822361',
    projectId: 'farmercompanion',
    storageBucket: 'farmercompanion.appspot.com',
    iosBundleId: 'com.example.flutterFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTEnKIVlijlOFJeJlcv9I1iMDu2sBUbBE',
    appId: '1:411403822361:web:5e8e257c03102656f29188',
    messagingSenderId: '411403822361',
    projectId: 'farmercompanion',
    authDomain: 'farmercompanion.firebaseapp.com',
    storageBucket: 'farmercompanion.appspot.com',
  );
}
